#! /bin/bash

# allow attach debugger
# -Xdebug -Xrunjdwp:transport=dt_socket,address=9092,server=y,suspend=n \

java -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 \
    -cp "$(lein classpath)" clojure.main -m {{sanitized-ns}}.main $@
